version: "3.7"

services:
  frontend:
    image: frontend
    container_name: frontend
    mem_limit: 1G
    cpus: 0.5
    ports:
        - "80:80"
    volumes:
        - ../frontend:/app
    networks:
      network:
        aliases:
          - frontend

networks:
  network:
    name: network
